action: ??? # train or test
name: ??? # name of the experiment needed for the logs
modality: ["all_feat"] # modality used
concat_feat: ["RGB","Audio","OptFlow"] # modality used
total_batch: 128 # total batch size if training is done with gradient accumulation
batch_size: 32 # batch size for the forward
gpus: null # gpus adopted
wandb_name: null # needed for wandb logging
resume_from: null # checkpoint directory
logname: null # name of the logs
models_dir: null # directory containing all the models

train:
  num_iter: 5000 # number of training iterations with total_batch size
  lr_steps: 3000 # steps before reducing learning rate
  eval_freq: 50 # evaluation frequency
  num_clips: 5 # clips adopted in training # was 1
  dense_sampling: # sampling version adopted in training for each modality
    RGB: True
  num_frames_per_clip: # number of frames adopted in training for each modality
    RGB: 16

test:
  num_clips: 5 # number of clips in testing
  dense_sampling: # sampling version adopted in test for each modality
    RGB: True
  num_frames_per_clip: # number of frames adopted in test for each modality
    RGB: 16

dataset:
  annotations_path: train_val # path for the annotations data
  shift: ??? # shifts of the dataset
  workers: 4 # number of workers for the dataloader
  stride: 2 # stride in case of dense sampling
  resolution: 224 # input resolution to the model
  RGB:
    tmpl: "img_{:010d}.jpg" # format of RGB filenames
    path: "rgb_features"
    features_name: saved_feat_I3D
  Audio:
    path: "audio_features"
    features_name: audio_feat
  OptFlow:
    path: "optflow_features"
    features_name: optflow_feat

# these are the action recognition models for each modality
models:
  model: Classifier
  frame_aggregation: 'trn' #'avgpool'
  weight:
    GSD: 0
    GVD: 0
    GRD: 0
    Attn: 0
  reduce_factor: 0.1
  RGB:
    normalize: False
    kwargs: {}
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  Audio:
    normalize: False
    kwargs: {}
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  OptFlow:
    normalize: False
    kwargs: {}
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  all_feat:
    normalize: False
    kwargs: {}
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
