from models.VideoModel import VideoModel
from models.I3D import I3D
from models.FullLayerClassifier import FullLayerClassifierTAP
from models.FullLayerClassifier import FullLayerClassifierTRN
from models.FullLayerClassifier import trainLoopFLC
from models.FullLayerClassifier import testLoopFLC
from models.TAPmodule import TemporalAveragePooling
from models.TRNmodule import RelationModuleMultiScale
